### PR TITLE
use jakarta project maven coordinates

### PR DESCRIPTION
**Pull request by olamy**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — COMMENTED** [review]
PR description is blank, lacking context and motivation.

Missing the analogous change to `jakarta-mail-api-plugin`.

Missing end-to-end testing.

**Review by basil — DISMISSED** [review]
In addition to the previous comments, this PR removes the following classes from this plugin:

```
com/sun/activation/registries/LineTokenizer.class
com/sun/activation/registries/LogSupport.class
com/sun/activation/registries/MailcapFile.class
com/sun/activation/registries/MailcapParseException.class
com/sun/activation/registries/MailcapTokenizer.class
com/sun/activation/registries/MimeTypeEntry.class
com/sun/activation/registries/MimeTypeFile.class
```

These are now in `org.eclipse.angus:angus-activation:jar:1.0.0`. In order to prevent regressions due to missing classes, a dependency on `org.eclipse.angus:angus-activation:jar:1.0.0` should be added to this plugin.

This would likely have been caught if the end-to-end testing described in my previous comment had been done.

**Comment by basil** [comment]
[YouTube video with more information](https://www.youtube.com/watch?v=gsNwC7K8URk)

**Review by basil — CHANGES_REQUESTED** [review]
> Missing the analogous change to `jakarta-mail-api-plugin`.

I added `angus-activation` in commit c73cc44f5bc6b1ddfd75c18ba2b01d27d1086d06 and filed https://github.com/jenkinsci/jakarta-mail-api-plugin/pull/30 with the downstream changes in the Jakarta Mail plugin. That PR is failing with:

```
Caused by: java.lang.ArrayStoreException
        at java.lang.System.arraycopy(Native Method)
        at java.util.Vector.copyInto(Vector.java:197)
        at jakarta.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:141)
        at jakarta.activation.FileTypeMap.getDefaultFileTypeMap(FileTypeMap.java:110)
        at io.jenkins.plugins.jakarta.activation.FileTypeMapInitializer.init(FileTypeMapInitializer.java:20)
        ... 14 more
```

`CommandMapInitializer` and `FileTypeMapInitializer` may not be necessary anymore (need to do end-to-end testing to find out), or the implementations may need to change to adapt to Angus Activation.

**Comment by hellBoy333k** [comment]
com/sun/activation/registries/LineTokenizer.class
com/sun/activation/registries/LogSupport.class
com/sun/activation/registries/MailcapFile.class
com/sun/activation/registries/MailcapParseException.class
com/sun/activation/registries/MailcapTokenizer.class
com/sun/activation/registries/MimeTypeEntry.class
com/sun/activation/registries/MimeTypeFile.class

**Pull request closed without merging**
